///DEFINIÇÃO DOS COMANDOS
#define CROOT 1
#define ADDNODE 2
#define REMOVE 3
#define DLEFT 4
#define DRIGHT 5
#define GO 6
#define BACK 7
#define GOROOT 8
#define TREE 9
#define DELTREE 10
#define HEIGHT 11
#define SIZE 12
#define LEAFS 13
#define LOADTREE 14
#define SAVETREE 15
#define WHEREAMI 16
#define QUIT 17
#define HELP 18
